services:
  redis:
    image: ghcr.io/saiemgilani/saiemgilani/game-on-paper-redis:latest
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 1gb
  cache:
    image: ghcr.io/saiemgilani/saiemgilani/game-on-paper-cache:latest
    expose:
      - 6380
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 1gb
  summary:
    image: ghcr.io/akeaswaran/akeaswaran/cfb-team-summaries:latest
    expose:
      - 3000
    healthcheck:
      test: curl --fail http://summary:3000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 1gb
  node:
    image: ghcr.io/saiemgilani/saiemgilani/game-on-paper-node:latest
    command: ["node", "server.js"]
    environment:
      RDATA_BASE_URL: "http://python:7000"
    ports:
      - 8000:8000
    depends_on:
      - python
      - summary
      - redis
      - cache
    links:
      - python
      - summary
      - redis
      - cache
    healthcheck:
      test: curl --fail http://localhost:8000/cfb/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        reservations:
          cpus: 1
          memory: 1gb
  python:
    image: ghcr.io/saiemgilani/saiemgilani/game-on-paper-python:latest
    expose:
      - 7000
    healthcheck:
      test: curl --fail http://python:7000/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        reservations:
          cpus: 1
          memory: 1gb
