import { range } from "./misc";

export const CURRENT_YEAR = 2026;
export const LAST_YEAR = 2025;
export const AVAILABLE_SEASONS = range(2004, CURRENT_YEAR);
export const ALPHABET = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"];
export const MEME_LIST = [61];
export const FBS_CONFERENCES = ['1','4','5','8','9','12','15','17','37','151','80', '18'];
export const NETWORK_MAPPINGS: Record<string, string> = {
    "FOX" : 'https://www.foxsports.com/live',
    "FS1" : 'https://www.foxsports.com/live/fs1',
    "FS2" : 'https://www.foxsports.com/live/fs2',
    "BTN" : 'https://www.foxsports.com/live/btn',
    "NBC" : 'https://www.nbcsports.com/live',
    "Peacock" : 'https://www.peacocktv.com',
    "CBSSN" : 'https://www.cbssports.com/cbs-sports-network/',
    "CBS" : 'https://www.cbssports.com/live/',
    'PAC12' : 'https://pac-12.com/live',
    'NFL NET' : 'https://www.nfl.com/network/watch/nfl-network-live',
    'CW NETWORK' : "https://www.cwtv.com/sports/",
    "CW" : "https://www.cwtv.com/sports/",
    "THE CW NETWORK" : "https://www.cwtv.com/sports/",
    "The CW Network" : "https://www.cwtv.com/sports/",
    "MWSN": "https://themw.com/watch/",
    "MWN": "https://themw.com/watch/",
    "MW+": "https://watch.themw.com",
    "MWN App": "https://themw.com/watch/",
    "truTV": "https://www.trutv.com/watchtrutv",
    "TNT": "https://www.tntdrama.com/watchtnt",
    "USA Net": "https://www.usanetwork.com/sports",
    "Scripps Sports": "https://scrippssportsnetwork.com/",
    "FloSports": "https://www.flocollege.com/sports/12787066-football",
    "MEAC Network": "https://watch.meacsports.com",
    "Midco Sports Plus": "https://www.midcosportsplus.com",
    "Midco Sports Net": "https://sports.midco.com",
    "NEC Front Row": "https://necfrontrow.com/schedule",
    "SWAC TV": "https://tv.swac.org",
    "MNMT": "https://www.monumentalsportsnetwork.com",
    "CIAA Network": "https://theciaasn.com",
    "HBCU GO": "https://hbcugo.tv/",
    "HBCU Go": "https://hbcugo.tv/",
    "UCONN+": "https://uconnhuskies.com/watch/",
    "UConn+": "https://uconnhuskies.com/watch/"
};

export function isESPNNetwork(networkName?: string | null): boolean {
    if (!networkName) {
        return false;
    }
    
    return (
        networkName.includes('ESPN') 
        || networkName.includes('LHN')
        || networkName.includes('Longhorn Network')
        || networkName.includes('ACCN')
        || networkName.includes('ACC Extra')
        || networkName.includes('ACC Network')
        || networkName.includes('SEC Network')
        || networkName.includes('SECN')
        || networkName.includes('BIG12')
        || networkName.includes('ABC')
    )
}

export const GAME_QUARANTINE_LIST = [
    "401411157",
    "401403861",
    "401628329",
    "401634301",
    "401634212",
    "401628398"
]

export const SPECIAL_IMAGES: { [teamId: string]: string} = {
    "61": "/assets/img/ennui-uga.png",
    "59": "/assets/img/gt-old-gold.png"
    // "2390": "/assets/img/upside-down-u.png",
};
export const SPECIAL_IMAGES_DARK: { [teamId: string]: string} = {
    "59": "/assets/img/gt-old-gold-dark.png"
    // "2390": "/assets/img/upside-down-u.png",
};

export const PLAYER_METRIC_CATEGORIES: Record<string, Record<string, string>> = {
    "passing": {
        "statistics.dropbacks": "Dropbacks",
        "statistics.sackAdjustedYards": "Sack-Adj Yds",
        "advanced.totalEPA": "EPA",
        "statistics.yardsPerDropback": "Yards/DB",
        "advanced.epaPerPlay": "EPA/DB",
        "advanced.successRate": "Pass SR%",
    }, 
    "rushing": {
        "statistics.plays": "Carries",
        "statistics.yards": "Yards",
        "advanced.totalEPA": "EPA",
        "statistics.yardsPerPlay": "Yards/Rush",
        "advanced.epaPerPlay": "EPA/Rush",
        "advanced.successRate": "Rush SR%",
    }, 
    "receiving": {
        "statistics.catches": "Catches",
        "statistics.targets": "Targets",
        "statistics.catchPct": "Catch %",
        "statistics.yards": "Yards",
        "advanced.totalEPA": "EPA",
        "statistics.yardsPerPlay": "Yards/Tgt",
        "advanced.epaPerPlay": "EPA/Tgt",
        "advanced.successRate": "Rec SR%",
    }
};

export const PLAYER_METRIC_FORMATTING_VALUES: Record<string, Record<string, number[]>> = {
    "passing": {
        "statistics.games": [1,2,0],
        "statistics.dropbacks": [1,2,0], // multiplier, power10, fixed
        "statistics.sackAdjustedYards": [1,2,1],
        "advanced.totalEPA": [1,2,2],
        "statistics.yardsPerDropback": [1,2,2],
        "advanced.epaPerPlay": [1,2,2],
        "advanced.successRate": [100,2,1],
    }, 
    "rushing": {
        "statistics.games": [1,2,0],
        "statistics.plays": [1,2,0],
        "statistics.yards": [1,2,1],
        "advanced.totalEPA": [1,2,2],
        "statistics.yardsPerPlay": [1,2,2],
        "advanced.epaPerPlay": [1,2,2],
        "advanced.successRate": [100,2,1],
    }, 
    "receiving": {
        "statistics.games": [1,2,0],
        "statistics.catches": [1,2,0],
        "statistics.targets": [1,2,0],
        "statistics.catchPct": [100,2,1],
        "statistics.yards": [1,2,1],
        "advanced.totalEPA": [1,2,2],
        "statistics.yardsPerPlay": [1,2,2],
        "advanced.epaPerPlay": [1,2,2],
        "advanced.successRate": [100,2,1],
    }
};

export const TEAM_METRIC_CATEGORIES: Record<string, Record<string, string>> = {
    "differential": {
        "overall.adjEpaPerPlay": "Adj EPA/Play",
        "overall.epaPerPlay": "EPA/Play",
        "overall.yardsPerPlay": "Yards/Play",
        "overall.successRate": "SR%",
    }, 
    "offensive": {
        "overall.adjEpaPerPlay": "Adj EPA/Play",
        "overall.epaPerPlay": "EPA/Play",
        "overall.yardsPerPlay": "Yards/Play",
        "overall.successRate": "SR%",

        "passing.epaPerPlay": "EPA/DB",
        "passing.yardsPerPlay": "Yards/DB",
        "passing.successRate": "Pass SR%",

        "rushing.epaPerPlay": "EPA/Rush",
        "rushing.yardsPerPlay": "Yards/Rush",
        "rushing.successRate": "Rush SR%",

        "overall.havocRate": "Havoc %"
    }, 
    "defensive": {
        "overall.adjEpaPerPlay": "Adj EPA/Play",
        "overall.epaPerPlay": "EPA/Play",
        "overall.yardsPerPlay": "Yards/Play",
        "overall.successRate": "SR%",

        "passing.epaPerPlay": "EPA/DB",
        "passing.yardsPerPlay": "Yards/DB",
        "passing.successRate": "Pass SR%",

        "rushing.epaPerPlay": "EPA/Rush",
        "rushing.yardsPerPlay": "Yards/Rush",
        "rushing.successRate": "Rush SR%",

        "overall.havocRate": "Havoc %"
    }
};

export const TEAM_METRIC_FORMATTING_VALUES: Record<string, Record<string, number[]>> = {
    "differential": {
        "overall.adjEpaPerPlay": [1,2,2],
        "overall.epaPerPlay": [1,2,2],
        "overall.yardsPerPlay": [1,2,2],
        "overall.successRate": [100,2,1],
    }, 
    "offensive": {
        "overall.adjEpaPerPlay": [1,2,2],
        "overall.epaPerPlay": [1,2,2],
        "overall.yardsPerPlay": [1,2,2],
        "overall.successRate": [100,2,1],  

        "passing.epaPerPlay": [1,2,2],
        "passing.yardsPerPlay": [1,2,2],
        "passing.successRate": [100,2,1], 

        "rushing.epaPerPlay": [1,2,2],
        "rushing.yardsPerPlay": [1,2,2],
        "rushing.successRate": [100,2,1], 

        "overall.havocRate": [100,2,1], 
    }, 
    "defensive": {
        "overall.adjEpaPerPlay": [1,2,2],
        "overall.epaPerPlay": [1,2,2],
        "overall.yardsPerPlay": [1,2,2],
        "overall.successRate": [100,2,1],  

        "passing.epaPerPlay": [1,2,2],
        "passing.yardsPerPlay": [1,2,2],
        "passing.successRate": [100,2,1], 

        "rushing.epaPerPlay": [1,2,2],
        "rushing.yardsPerPlay": [1,2,2],
        "rushing.successRate": [100,2,1], 

        "overall.havocRate": [100,2,1], 
    }
};

export const TEAM_METRIC_HOVER_TEXT: Record<string, Record<string, string>> = {
    "differential": {
        "overall.adjEpaPerPlay": "Accounts for home-field advantange, accounting for home-field advantage, quality of opponent, and garbage time in FBS vs FBS games.",
    }, 
    "offensive": {
        "overall.adjEpaPerPlay": "Accounts for home-field advantange, accounting for home-field advantage, quality of opponent, and garbage time in FBS vs FBS games.",
        "passing.epaPerPlay": "DB: Dropbacks, includes pass attempts and sacks.",
        "passing.yardsPerPlay": "DB: Dropbacks, includes pass attempts and sacks.",
    }, 
    "defensive": {
        "overall.adjEpaPerPlay": "Accounts for home-field advantange, accounting for home-field advantage, quality of opponent, and garbage time in FBS vs FBS games.",
        "passing.epaPerPlay": "DB: Dropbacks, includes pass attempts and sacks.",
        "passing.yardsPerPlay": "DB: Dropbacks, includes pass attempts and sacks.",
    }
};


export const METRIC_KEY_TITLE_MAPPING: Record<string, string> = {
    "EPA_plays" : "Total Plays",
    "scrimmage_plays" : "Scrimmage Plays",
    "EPA_overall_total" : "Total EPA",
    "EPA_overall_off" : "&emsp;&emsp;EPA",
    "EPA_overall_offense" : "&emsp;&emsp;Offensive EPA",
    "EPA_passing_overall" : "&emsp;&emsp;EPA",
    "EPA_rushing_overall" : "&emsp;&emsp;EPA",
    "EPA_per_play" : "&emsp;&emsp;EPA/Play",
    "EPA_passing_per_play" : "&emsp;&emsp;EPA/Play",
    "EPA_rushing_per_play" : "&emsp;&emsp;EPA/Play",
    "rushes" : "Rushes",
    "rushing_power" : "&emsp;&emsp;Power Run Attempts (Down &#8805; 3, Distance &#8804; 2)",
    "rushing_power_success" : "&emsp;&emsp;Successful Power Runs (Rate)",
    "rushing_stuff" : "&emsp;&emsp;Stuffed Runs (Yds Gained &#8804; 0)",
    "rushing_stopped" : "&emsp;&emsp;Stopped Runs (Yds Gained &#8804; 2)",
    "rushing_opportunity" : "&emsp;&emsp;Opportunity Runs (Yds Gained &#8805; 4)",
    "rushing_highlight" : "&emsp;&emsp;Highlight Runs (Yds Gained &#8805; 8)",
    "havoc_total" : "Havoc Plays Created",
    "havoc_total_pass" : "&emsp;&emsp;Passing",
    "havoc_total_rush" : "&emsp;&emsp;Rushing",
    "EPA_penalty": "&emsp;&emsp;Penalty EPA",
    "special_teams_plays" : "Total Plays",
    "EPA_sp" : "Total EPA",
    "EPA_special_teams" : "&emsp;&emsp;Special Teams EPA",
    "EPA_fg" : "&emsp;&emsp;Field Goal EPA",
    "EPA_punt" : "&emsp;&emsp;Punting EPA",
    "EPA_kickoff" : "&emsp;&emsp;Kickoff Return EPA",
    "TFL" : "TFLs Generated",
    "TFL_pass" : "&emsp;&emsp;Passing",
    "TFL_rush" : "&emsp;&emsp;Rushing",
    "EPA_success" : "Successful Plays (EPA > 0)",
    "EPA_success_pass" : "&emsp;&emsp;When Passing",
    "EPA_success_rush" : "&emsp;&emsp;When Rushing",
    "EPA_success_standard_down" : "&emsp;&emsp;On Standard Downs",
    "EPA_success_passing_down": "&emsp;&emsp;On Passing Downs",
    "EPA_success_early_down": "&emsp;&emsp;On Early Downs",
    "EPA_success_early_down_pass": "&emsp;&emsp;Successful Passes (Rate)",
    "EPA_success_early_down_rush": "&emsp;&emsp;Successful Rushes (Rate)",
    "early_downs": "Early Downs",
    "early_down_pass": "&emsp;&emsp;Passes",
    "early_down_rush": "&emsp;&emsp;Rushes",
    "EPA_success_late_down": "&emsp;&emsp;On Late Downs",
    "EPA_success_late_down_pass": "&emsp;&emsp;Successful Passes (Rate)",
    "EPA_success_late_down_rush": "&emsp;&emsp;Successful Rushes (Rate)",
    "late_downs": "Late Downs",
    "late_down_pass": "&emsp;&emsp;Passes",
    "late_down_rush": "&emsp;&emsp;Rushes",
    "EPA_explosive" : "Explosive Plays",
    "EPA_explosive_passing" : "&emsp;&emsp;When Passing (EPA > 2.4)",
    "EPA_explosive_rushing" : "&emsp;&emsp;When Rushing (EPA > 1.8)",
    "scoring_opps_opportunities" : "Scoring Opps",
    "scoring_opps_points" : "&emsp;&emsp;Total Points",
    "scoring_opps_pts_per_opp" : "&emsp;&emsp;Points per Opp",
    "field_pos_avg_start" : "Avg Starting FP",
    "field_pos_avg_starting_predicted_pts" : "&emsp;&emsp;Predicted Points",
    "sacks" : "Sacks Generated",
    "turnovers" : "Turnovers",
    "expected_turnovers" : "Expected Turnovers",
    "turnover_margin" : "Turnover Margin",
    "expected_turnover_margin" : "Expected Turnover Margin",
    "turnover_luck" : "Turnover Luck (pts)",
    "PD" : "Passes Defensed",
    "INT" : "&emsp;&emsp;Interceptions",
    "Int" : "&emsp;&emsp;Interceptions",
    "def_int" : "Interceptions",
    "fumbles" : "Fumbles Forced",
    "total_fumbles" : "&emsp;&emsp;Fumbles",
    "fumbles_lost" : "&emsp;&emsp;Fumbles Lost",
    "fumbles_recovered" : "&emsp;&emsp;Fumbles Recovered",
    "middle_8": "\"Middle 8\" Plays",
    "middle_8_pass": "&emsp;&emsp;Passes",
    "middle_8_rush": "&emsp;&emsp;Rushes",
    "EPA_middle_8": "&emsp;&emsp;EPA",
    "EPA_middle_8_success": "&emsp;&emsp;During \"Middle 8\"",
    "EPA_middle_8_success_pass": "&emsp;&emsp;Successful Passes (Rate)",
    "EPA_middle_8_success_rush": "&emsp;&emsp;Successful Rushes (Rate)",
    "EPA_middle_8_per_play" : "&emsp;&emsp;EPA/play",
    "EPA_early_down" : "&emsp;&emsp;EPA",
    "EPA_early_down_per_play" : "&emsp;&emsp;EPA/Play",
    "EPA_late_down" : "&emsp;&emsp;EPA",
    "EPA_late_down_per_play" : "&emsp;&emsp;EPA/Play",
    "late_down_avg_distance" : "&emsp;&emsp;Avg Distance",
    "first_downs_created" : "First Downs Created",
    "early_down_first_down" : "&emsp;&emsp;First Downs Created",
    "passes" : "Passes",
    "drives" : "Total",
    "drive_total_gained_yards_rate" : "Available Yards %",
    "yards_per_drive" : "Yards/Drive",
    "plays_per_drive" : "Plays/Drive",
    "avg_field_position": "Avg Starting Field Position",
    "rushing_highlight_yards": "<a href=\"https://www.footballstudyhall.com/2018/2/2/16963820/college-football-advanced-stats-glossary\">Highlight Yards</a>",
    "rushing_highlight_yards_per_opp": "&emsp;&emsp;Per Rush Opportunity",
    "line_yards": "<a href=\"https://www.footballstudyhall.com/2018/2/2/16963820/college-football-advanced-stats-glossary\">OL Line Yards</a>",
    "line_yards_per_carry": "&emsp;&emsp;Per Carry",
    "yards_per_rush": "&emsp;&emsp;Yards/Play",
    "yards_per_pass": "&emsp;&emsp;Yards/Play",
    "yards_per_play": "&emsp;&emsp;Yards/Play",
    "off_yards" : "&emsp;&emsp;Yards",
    "rush_yards" : "&emsp;&emsp;Yards",
    "pass_yards" : "&emsp;&emsp;Yards",
    "total_yards":  "Total Yards",
    "total_off_yards" : "&emsp;&emsp;Offensive Yards",
    "total_sp_yards":"&emsp;&emsp;Special Teams Yards",
    "total_pen_yards":"&emsp;&emsp;Penalty Yards",
    "EPA_misc" : "&emsp;&emsp;Non-Scrimmage/Misc EPA",
    "open_field_yards" : "Open-Field Yards",
    "second_level_yards" : "Second-Level Yards",
    "drive_stopped_rate" : "<a href=\"https://theathletic.com/2419632/2021/03/02/college-football-defense-rankings-stop-rate/\">Stop Rate</a>",
    "EPA_non_explosive" : "EPA w/o Explosive Plays",
    "EPA_non_explosive_per_play" : "&emsp;&emsp;EPA/Play",
    "EPA_non_explosive_passing" : "&emsp;&emsp;When Passing",
    "EPA_non_explosive_passing_per_play" : "&emsp;&emsp;&emsp;&emsp;EPA/Play",
    "EPA_non_explosive_rushing" : "&emsp;&emsp;When Rushing",
    "EPA_non_explosive_rushing_per_play" : "&emsp;&emsp;&emsp;&emsp;EPA/Play"
};

export const TURNOVER_VEC: string[] = [
    "Blocked Field Goal",
    "Blocked Field Goal Touchdown",
    "Blocked Punt",
    "Blocked Punt Touchdown",
    "Field Goal Missed",
    "Missed Field Goal Return",
    "Missed Field Goal Return Touchdown",
    "Fumble Recovery (Opponent)",
    "Fumble Recovery (Opponent) Touchdown",
    "Fumble Return Touchdown",
    "Defensive 2pt Conversion",
    "Interception",
    "Interception Return",
    "Interception Return Touchdown",
    "Pass Interception Return",
    "Pass Interception Return Touchdown",
    "Kickoff Team Fumble Recovery",
    "Kickoff Team Fumble Recovery Touchdown",
    "Punt Touchdown",
    "Punt Return Touchdown",
    "Sack Touchdown",
    "Uncategorized Touchdown"
]

export const BOX_SCORE_NON_RATE_DECIMAL_COLUMNS: string[] = ["expected_turnovers","expected_turnover_margin","turnover_luck","EPA_middle_8_per_play","EPA_middle_8","EPA_middle_8_per_play","EPA_middle_8","EPA_early_down_per_play","EPA_early_down","EPA_sp","EPA_special_teams","EPA_kickoff","EPA_punt","EPA_fg","EPA_overall_off","EPA_per_play","EPA_passing_overall","EPA_passing_per_play", "EPA_rushing_overall","EPA_rushing_per_play","points_per_drive","yards_per_drive","plays_per_drive","avg_field_position","rushing_highlight_yards_per_opp","line_yards_per_carry","yards_per_rush","yards_per_pass","yards_per_play","drive_stopped_rate","EPA_non_explosive","EPA_non_explosive_passing","EPA_non_explosive_rushing","EPA_non_explosive_per_play","EPA_non_explosive_passing_per_play","EPA_non_explosive_rushing_per_play", "EPA_late_down_per_play", "EPA_late_down", "late_down_avg_distance"];
export const BOX_SCORE_NON_RATE_COLUMNS: string[] = ["EPA_plays","scrimmage_plays","expected_turnover_margin","turnover_margin","turnovers","expected_turnovers","turnover_luck","early_downs","late_downs","fumbles","INT","PD","middle_8","EPA_middle_8_per_play","EPA_middle_8","EPA_early_down_per_play","EPA_early_down","fumbles_lost","fumbles_recovered","Int","TFL","TFL_pass","TFL_rush","total_fumbles","def_int","points_per_drive","drives","points_per_drive","yards_per_drive","plays_per_drive","drive_total_gained_yards_rate","avg_field_position","rushing_highlight_yards","line_yards","yards_per_rush","yards_per_pass","yards_per_play","off_yards","pass_yards","rush_yards","EPA_overall_offense","EPA_penalty","EPA_overall_total","second_level_yards","open_field_yards","drive_stopped_rate","EPA_non_explosive","EPA_non_explosive_passing","EPA_non_explosive_rushing","EPA_non_explosive_per_play","EPA_non_explosive_passing_per_play","EPA_non_explosive_rushing_per_play"]; 
export const BOX_SCORE_NON_RATE_PERCENT_COLUMNS: string[] = ["drive_total_gained_yards_rate","drive_stopped_rate","EPA_success_rate_third","EPA_success_rate_rz"];



export const SDV_TEAM_SUMMARY_AVAILABLE_COLUMNS = [
    "team_id",
    "pos_team",
    "division",
    "conference",
    "season",
    "plays_off",
    "playsgame_off",
    "passrate_off",
    "rushrate_off",
    "havoc_off",
    "explosive_off",
    "TEPA_off",
    "EPAplay_off",
    "EPAdrive_off",
    "EPAgame_off",
    "yards_off",
    "yardsplay_off",
    "yardsgame_off",
    "play_stuffed_off",
    "drives_off",
    "drivesgame_off",
    "yardsdrive_off",
    "playsdrive_off",
    "success_off",
    "red_zone_success_off",
    "third_down_success_off",
    "third_down_distance_off",
    "late_down_success_off",
    "early_down_EPA_off",
    "start_position_off",
    "nonExplosiveEpaPerPlay_off",
    "line_yards_off",
    "opportunity_rate_off",
    "playsgame_off_rank",
    "TEPA_off_rank",
    "EPAgame_off_rank",
    "EPAplay_off_rank",
    "EPAdrive_off_rank",
    "early_down_EPA_off_rank",
    "success_off_rank",
    "yards_off_rank",
    "yardsplay_off_rank",
    "yardsgame_off_rank",
    "drivesgame_off_rank",
    "yardsdrive_off_rank",
    "playsdrive_off_rank",
    "play_stuffed_off_rank",
    "red_zone_success_off_rank",
    "third_down_success_off_rank",
    "late_down_success_off_rank",
    "third_down_distance_off_rank",
    "start_position_off_rank",
    "havoc_off_rank",
    "explosive_off_rank",
    "passrate_off_rank",
    "rushrate_off_rank",
    "nonExplosiveEpaPerPlay_off_rank",
    "line_yards_off_rank",
    "opportunity_rate_off_rank",
    "plays_def",
    "playsgame_def",
    "passrate_def",
    "rushrate_def",
    "havoc_def",
    "explosive_def",
    "TEPA_def",
    "EPAplay_def",
    "EPAdrive_def",
    "EPAgame_def",
    "yards_def",
    "yardsplay_def",
    "yardsgame_def",
    "play_stuffed_def",
    "drives_def",
    "drivesgame_def",
    "yardsdrive_def",
    "playsdrive_def",
    "success_def",
    "red_zone_success_def",
    "third_down_success_def",
    "third_down_distance_def",
    "late_down_success_def",
    "early_down_EPA_def",
    "start_position_def",
    "nonExplosiveEpaPerPlay_def",
    "line_yards_def",
    "opportunity_rate_def",
    "playsgame_def_rank",
    "TEPA_def_rank",
    "EPAgame_def_rank",
    "EPAplay_def_rank",
    "EPAdrive_def_rank",
    "early_down_EPA_def_rank",
    "success_def_rank",
    "yards_def_rank",
    "yardsplay_def_rank",
    "yardsgame_def_rank",
    "drivesgame_def_rank",
    "yardsdrive_def_rank",
    "playsdrive_def_rank",
    "play_stuffed_def_rank",
    "red_zone_success_def_rank",
    "third_down_success_def_rank",
    "late_down_success_def_rank",
    "third_down_distance_def_rank",
    "start_position_def_rank",
    "havoc_def_rank",
    "explosive_def_rank",
    "passrate_def_rank",
    "rushrate_def_rank",
    "nonExplosiveEpaPerPlay_def_rank",
    "line_yards_def_rank",
    "opportunity_rate_def_rank",
    "TEPA_margin",
    "EPAplay_margin",
    "EPAdrive_margin",
    "EPAgame_margin",
    "success_margin",
    "yardsplay_margin",
    "TEPA_margin_rank",
    "EPAgame_margin_rank",
    "EPAdrive_margin_rank",
    "EPAplay_margin_rank",
    "success_margin_rank",
    "yardsplay_margin_rank",
    "start_position_margin",
    "start_position_margin_rank",
    "total_available_yards_off",
    "total_gained_yards_off",
    "available_yards_pct_off",
    "available_yards_pct_off_rank",
    "total_available_yards_def",
    "total_gained_yards_def",
    "available_yards_pct_def",
    "available_yards_pct_def_rank",
    "total_available_yards_margin",
    "total_gained_yards_margin",
    "available_yards_pct_margin",
    "total_available_yards_margin_rank",
    "total_gained_yards_margin_rank",
    "available_yards_pct_margin_rank",
    "plays_off_pass",
    "playsgame_off_pass",
    "passrate_off_pass",
    "rushrate_off_pass",
    "havoc_off_pass",
    "explosive_off_pass",
    "TEPA_off_pass",
    "EPAplay_off_pass",
    "EPAdrive_off_pass",
    "EPAgame_off_pass",
    "yards_off_pass",
    "yardsplay_off_pass",
    "yardsgame_off_pass",
    "play_stuffed_off_pass",
    "drives_off_pass",
    "drivesgame_off_pass",
    "yardsdrive_off_pass",
    "playsdrive_off_pass",
    "success_off_pass",
    "red_zone_success_off_pass",
    "third_down_success_off_pass",
    "third_down_distance_off_pass",
    "late_down_success_off_pass",
    "early_down_EPA_off_pass",
    "nonExplosiveEpaPerPlay_off_pass",
    "line_yards_off_pass",
    "opportunity_rate_off_pass",
    "playsgame_off_pass_rank",
    "TEPA_off_pass_rank",
    "EPAgame_off_pass_rank",
    "EPAplay_off_pass_rank",
    "EPAdrive_off_pass_rank",
    "early_down_EPA_off_pass_rank",
    "success_off_pass_rank",
    "yards_off_pass_rank",
    "yardsplay_off_pass_rank",
    "yardsgame_off_pass_rank",
    "drivesgame_off_pass_rank",
    "yardsdrive_off_pass_rank",
    "playsdrive_off_pass_rank",
    "play_stuffed_off_pass_rank",
    "red_zone_success_off_pass_rank",
    "third_down_success_off_pass_rank",
    "late_down_success_off_pass_rank",
    "third_down_distance_off_pass_rank",
    "havoc_off_pass_rank",
    "explosive_off_pass_rank",
    "passrate_off_pass_rank",
    "rushrate_off_pass_rank",
    "nonExplosiveEpaPerPlay_off_pass_rank",
    "line_yards_off_pass_rank",
    "opportunity_rate_off_pass_rank",
    "plays_def_pass",
    "playsgame_def_pass",
    "passrate_def_pass",
    "rushrate_def_pass",
    "havoc_def_pass",
    "explosive_def_pass",
    "TEPA_def_pass",
    "EPAplay_def_pass",
    "EPAdrive_def_pass",
    "EPAgame_def_pass",
    "yards_def_pass",
    "yardsplay_def_pass",
    "yardsgame_def_pass",
    "play_stuffed_def_pass",
    "drives_def_pass",
    "drivesgame_def_pass",
    "yardsdrive_def_pass",
    "playsdrive_def_pass",
    "success_def_pass",
    "red_zone_success_def_pass",
    "third_down_success_def_pass",
    "third_down_distance_def_pass",
    "late_down_success_def_pass",
    "early_down_EPA_def_pass",
    "nonExplosiveEpaPerPlay_def_pass",
    "line_yards_def_pass",
    "opportunity_rate_def_pass",
    "playsgame_def_pass_rank",
    "TEPA_def_pass_rank",
    "EPAgame_def_pass_rank",
    "EPAplay_def_pass_rank",
    "EPAdrive_def_pass_rank",
    "early_down_EPA_def_pass_rank",
    "success_def_pass_rank",
    "yards_def_pass_rank",
    "yardsplay_def_pass_rank",
    "yardsgame_def_pass_rank",
    "drivesgame_def_pass_rank",
    "yardsdrive_def_pass_rank",
    "playsdrive_def_pass_rank",
    "play_stuffed_def_pass_rank",
    "red_zone_success_def_pass_rank",
    "third_down_success_def_pass_rank",
    "late_down_success_def_pass_rank",
    "third_down_distance_def_pass_rank",
    "havoc_def_pass_rank",
    "explosive_def_pass_rank",
    "passrate_def_pass_rank",
    "rushrate_def_pass_rank",
    "nonExplosiveEpaPerPlay_def_pass_rank",
    "line_yards_def_pass_rank",
    "opportunity_rate_def_pass_rank",
    "TEPA_margin_pass",
    "EPAplay_margin_pass",
    "EPAdrive_margin_pass",
    "EPAgame_margin_pass",
    "success_margin_pass",
    "yardsplay_margin_pass",
    "TEPA_margin_pass_rank",
    "EPAgame_margin_pass_rank",
    "EPAdrive_margin_pass_rank",
    "EPAplay_margin_pass_rank",
    "success_margin_pass_rank",
    "yardsplay_margin_pass_rank",
    "plays_off_rush",
    "playsgame_off_rush",
    "passrate_off_rush",
    "rushrate_off_rush",
    "havoc_off_rush",
    "explosive_off_rush",
    "TEPA_off_rush",
    "EPAplay_off_rush",
    "EPAdrive_off_rush",
    "EPAgame_off_rush",
    "yards_off_rush",
    "yardsplay_off_rush",
    "yardsgame_off_rush",
    "play_stuffed_off_rush",
    "drives_off_rush",
    "drivesgame_off_rush",
    "yardsdrive_off_rush",
    "playsdrive_off_rush",
    "success_off_rush",
    "red_zone_success_off_rush",
    "third_down_success_off_rush",
    "third_down_distance_off_rush",
    "late_down_success_off_rush",
    "early_down_EPA_off_rush",
    "nonExplosiveEpaPerPlay_off_rush",
    "line_yards_off_rush",
    "opportunity_rate_off_rush",
    "playsgame_off_rush_rank",
    "TEPA_off_rush_rank",
    "EPAgame_off_rush_rank",
    "EPAplay_off_rush_rank",
    "EPAdrive_off_rush_rank",
    "early_down_EPA_off_rush_rank",
    "success_off_rush_rank",
    "yards_off_rush_rank",
    "yardsplay_off_rush_rank",
    "yardsgame_off_rush_rank",
    "drivesgame_off_rush_rank",
    "yardsdrive_off_rush_rank",
    "playsdrive_off_rush_rank",
    "play_stuffed_off_rush_rank",
    "red_zone_success_off_rush_rank",
    "third_down_success_off_rush_rank",
    "late_down_success_off_rush_rank",
    "third_down_distance_off_rush_rank",
    "havoc_off_rush_rank",
    "explosive_off_rush_rank",
    "passrate_off_rush_rank",
    "rushrate_off_rush_rank",
    "nonExplosiveEpaPerPlay_off_rush_rank",
    "line_yards_off_rush_rank",
    "opportunity_rate_off_rush_rank",
    "plays_def_rush",
    "playsgame_def_rush",
    "passrate_def_rush",
    "rushrate_def_rush",
    "havoc_def_rush",
    "explosive_def_rush",
    "TEPA_def_rush",
    "EPAplay_def_rush",
    "EPAdrive_def_rush",
    "EPAgame_def_rush",
    "yards_def_rush",
    "yardsplay_def_rush",
    "yardsgame_def_rush",
    "play_stuffed_def_rush",
    "drives_def_rush",
    "drivesgame_def_rush",
    "yardsdrive_def_rush",
    "playsdrive_def_rush",
    "success_def_rush",
    "red_zone_success_def_rush",
    "third_down_success_def_rush",
    "third_down_distance_def_rush",
    "late_down_success_def_rush",
    "early_down_EPA_def_rush",
    "nonExplosiveEpaPerPlay_def_rush",
    "line_yards_def_rush",
    "opportunity_rate_def_rush",
    "playsgame_def_rush_rank",
    "TEPA_def_rush_rank",
    "EPAgame_def_rush_rank",
    "EPAplay_def_rush_rank",
    "EPAdrive_def_rush_rank",
    "early_down_EPA_def_rush_rank",
    "success_def_rush_rank",
    "yards_def_rush_rank",
    "yardsplay_def_rush_rank",
    "yardsgame_def_rush_rank",
    "drivesgame_def_rush_rank",
    "yardsdrive_def_rush_rank",
    "playsdrive_def_rush_rank",
    "play_stuffed_def_rush_rank",
    "red_zone_success_def_rush_rank",
    "third_down_success_def_rush_rank",
    "late_down_success_def_rush_rank",
    "third_down_distance_def_rush_rank",
    "havoc_def_rush_rank",
    "explosive_def_rush_rank",
    "passrate_def_rush_rank",
    "rushrate_def_rush_rank",
    "nonExplosiveEpaPerPlay_def_rush_rank",
    "line_yards_def_rush_rank",
    "opportunity_rate_def_rush_rank",
    "TEPA_margin_rush",
    "EPAplay_margin_rush",
    "EPAdrive_margin_rush",
    "EPAgame_margin_rush",
    "success_margin_rush",
    "yardsplay_margin_rush",
    "TEPA_margin_rush_rank",
    "EPAgame_margin_rush_rank",
    "EPAdrive_margin_rush_rank",
    "EPAplay_margin_rush_rank",
    "success_margin_rush_rank",
    "yardsplay_margin_rush_rank",
    "fbs_class",
    "valid_games",
    "adj_off_epa",
    "adj_def_epa",
    "def_strength_faced",
    "off_strength_faced",
    "net_adj_epa",
    "adj_off_epa_rank",
    "adj_def_epa_rank",
    "net_adj_epa_rank",
]

export const SDV_TEAM_METRIC_CATEGORIES: Record<string, Record<string, string>> = {
    "differential": {
        "net_adj_epa": "Adj EPA/Play",
        "EPAplay_margin": "EPA/Play",
        "yardsplay_margin": "Yards/Play",
        "success_margin": "SR%",
    },
    "offensive": {
        "adj_off_epa": "Adj EPA/Play",
        "EPAplay_off": "EPA/Play",
        "yardsplay_off": "Yards/Play",
        "success_off": "SR%",

        "EPAplay_off_pass": "EPA/DB",
        "yardsplay_off_pass": "Yards/DB",
        "success_off_pass": "Pass SR%",

        "EPAplay_off_rush": "EPA/Rush",
        "yardsplay_off_rush": "Yards/Rush",
        "success_off_rush": "Rush SR%",

        "havoc_off": "Havoc %"
    }, 
    "defensive": {
        "adj_def_epa": "Adj EPA/Play",
        "EPAplay_def": "EPA/Play",
        "yardsplay_def": "Yards/Play",
        "success_def": "SR%",

        "EPAplay_def_pass": "EPA/DB",
        "yardsplay_def_pass": "Yards/DB",
        "success_def_pass": "Pass SR%",

        "EPAplay_def_rush": "EPA/Rush",
        "yardsplay_def_rush": "Yards/Rush",
        "success_def_rush": "Rush SR%",

        "havoc_def": "Havoc %"
    }
}

export const SDV_TEAM_METRIC_FORMATTING_VALUES: Record<string, Record<string, number[]>> = {
    "differential": {
        "net_adj_epa": [ 1, 2, 2 ],
        "EPAplay_margin": [ 1, 2, 2 ],
        "yardsplay_margin": [ 1, 2, 2 ],
        "success_margin": [ 100, 2, 1 ]
    }, 
    "offensive": {
        "adj_off_epa": [ 1, 2, 2 ],
        "EPAplay_off": [ 1, 2, 2 ],
        "yardsplay_off": [ 1, 2, 2 ],
        "success_off": [ 100, 2, 1 ],
        "EPAplay_off_pass": [ 1, 2, 2 ],
        "yardsplay_off_pass": [ 1, 2, 2 ],
        "success_off_pass": [ 100, 2, 1 ],
        "EPAplay_off_rush": [ 1, 2, 2 ],
        "yardsplay_off_rush": [ 1, 2, 2 ],
        "success_off_rush": [ 100, 2, 1 ],
        "havoc_off": [ 100, 2, 1 ]
    }, 
    "defensive": {
        "adj_def_epa": [ 1, 2, 2 ],
        "EPAplay_def": [ 1, 2, 2 ],
        "yardsplay_def": [ 1, 2, 2 ],
        "success_def": [ 100, 2, 1 ],
        "EPAplay_def_pass": [ 1, 2, 2 ],
        "yardsplay_def_pass": [ 1, 2, 2 ],
        "success_def_pass": [ 100, 2, 1 ],
        "EPAplay_def_rush": [ 1, 2, 2 ],
        "yardsplay_def_rush": [ 1, 2, 2 ],
        "success_def_rush": [ 100, 2, 1 ],
        "havoc_def": [ 100, 2, 1 ]
    }
};

export const SDV_TEAM_METRIC_HOVER_TEXT: Record<string, Record<string, string>> = {
    "differential": {
        "net_adj_epa": "Accounts for home-field advantange, accounting for home-field advantage, quality of opponent, and garbage time in FBS vs FBS games.",
    }, 
    "offensive": {
        "adj_off_epa": "Accounts for home-field advantange, accounting for home-field advantage, quality of opponent, and garbage time in FBS vs FBS games.",
        "EPAplay_off_pass": "DB: Dropbacks, includes pass attempts and sacks.",
        "yardsplay_off_pass": "DB: Dropbacks, includes pass attempts and sacks.",
    }, 
    "defensive": {
        "adj_def_epa": "Accounts for home-field advantange, accounting for home-field advantage, quality of opponent, and garbage time in FBS vs FBS games.",
        "EPAplay_def_pass": "DB: Dropbacks, includes pass attempts and sacks.",
        "yardsplay_def_pass": "DB: Dropbacks, includes pass attempts and sacks.",
    }
};

export const SDV_PLAYER_METRIC_CATEGORIES: Record<string, Record<string, string>> = {
    "passing": {
        "dropbacks": "Dropbacks",
        "sack_adj_yards": "Sack-Adj Yds",
        "TEPA": "EPA",
        "yardsdropback": "Yards/DB",
        "EPAplay": "EPA/DB",
        "success": "Pass SR%",
    }, 
    "rushing": {
        "plays": "Carries",
        "yards": "Yards",
        "TEPA": "EPA",
        "yardsplay": "Yards/Rush",
        "EPAplay": "EPA/Rush",
        "success": "Rush SR%",
    }, 
    "receiving": {
        "comp": "Catches",
        "targets": "Targets",
        "catchpct": "Catch %",
        "yards": "Yards",
        "TEPA": "EPA",
        "yardsplay": "Yards/Tgt",
        "EPAplay": "EPA/Tgt",
        "success": "Rec SR%",
    }
};

export const SDV_PLAYER_METRIC_FORMATTING_VALUES: Record<string, Record<string, number[]>> = {
    "passing": {
        "games": [1,2,0],
        "dropbacks": [1,2,0], // multiplier, power10, fixed
        "sack_adj_yards": [1,2,1],
        "TEPA": [1,2,2],
        "yardsdropback": [1,2,2],
        "EPAplay": [1,2,2],
        "success": [100,2,1],
    }, 
    "rushing": {
        "games": [1,2,0],
        "plays": [1,2,0],
        "yards": [1,2,1],
        "TEPA": [1,2,2],
        "yardsplay": [1,2,2],
        "EPAplay": [1,2,2],
        "success": [100,2,1],
    }, 
    "receiving": {
        "games": [1,2,0],
        "comp": [1,2,0],
        "targets": [1,2,0],
        "catchpct": [100,2,1],
        "yards": [1,2,1],
        "TEPA": [1,2,2],
        "yardsplay": [1,2,2],
        "EPAplay": [1,2,2],
        "success": [100,2,1],
    }
};

export const SDV_PLAYER_PERCENT_COLUMNS: string[] = [
    "success",
    "catchpct"
];

export const SDV_TEAM_PERCENT_COLUMNS: string[] = [
    "success",
    "success_off",
    "success_def",
    "success_off_pass",
    "success_def_pass",
    "success_off_rush",
    "success_def_rush",
    "success_margin",
    "havoc",
    "havoc_off",
    "havoc_def",
    "havoc_margin",
    "play_stuffed",
    "play_stuffed_off",
    "play_stuffed_def",
    "red_zone_success",
    "red_zone_success_off",
    "red_zone_success_def",
    "early_down_success",
    "early_down_success_off",
    "early_down_success_def",
    "late_down_success",
    "late_down_success_off",
    "late_down_success_def",
    "opportunity_rate",
    "opportunity_rate_off",
    "opportunity_rate_def",
    "opportunity_run",
    "explosive",
    "explosive_pass",
    "explosive_rush",
    "explosive_off",
    "explosive_off_pass",
    "explosive_off_rush",
    "explosive_def",
    "explosive_def_pass",
    "explosive_def_rush",
    "passrate",
    "rushrate",
    "passrate_off",
    "rushrate_off",
    "passrate_def",
    "rushrate_def"
];

export const SDV_RADAR_COLUMNS: Record<string, string[]> = {
    "differential": [],
    "defensive": [
        "EPAplay_def",
        "early_down_EPA_def",
        "late_down_success_def",
        "third_down_distance_def",
        "EPAplay_def_rush",
        "play_stuffed_def",
        "line_yards_def",
        "opportunity_rate_def",
        "explosive_def",
        "explosive_def_pass",
        "explosive_def_rush",
        "nonExplosiveEpaPerPlay_def",
        "EPAplay_def_pass",
        "yardsplay_def_pass",
        "success_def_pass",
        "havoc_def",
    ],
    "offensive": [
        "EPAplay_off",
        "early_down_EPA_off",
        "late_down_success_off",
        "third_down_distance_off",
        "EPAplay_off_rush",
        "play_stuffed_off",
        "line_yards_off",
        "opportunity_rate_off",
        "explosive_off",
        "explosive_off_pass",
        "explosive_off_rush",
        "nonExplosiveEpaPerPlay_off",
        "EPAplay_off_pass",
        "yardsplay_off_pass",
        "success_off_pass",
        "havoc_off",
    ]
}

export const SDV_TEAM_CARD_COLUMNS: Record<string, string[]> = {
    "differential": [
        "available_yards_pct_margin",
        "yardsplay_margin",
        "EPAplay_margin",
        "start_position_margin",
        "EPAdrive_margin"
    ],
    "defensive": [
        "start_position_def",
        "available_yards_pct_def",
        "yardsplay_def",
        "EPAplay_def",
        "EPAdrive_def"
    ],
    "offensive": [
        "start_position_off",
        "available_yards_pct_off",
        "yardsplay_off",
        "EPAplay_off",
        "EPAdrive_off"
    ]
}

export const SDV_BASE_METRIC_TITLES: Record<string, string> = {
  "plays": "Total Plays",
  "playsgame": "Plays/Game",
  "passrate": "Pass %",
  "rushrate": "Rush %",
  "havoc": "Havoc %",
  "explosive": "Explosive %",
  "TEPA": "Total EPA",
  "EPAplay": "EPA/Play",
  "EPAdrive": "EPA/Drive",
  "EPAgame": "EPA/Game",
  "yards": "Total Yards",
  "yardsplay": "Yards/Play",
  "yardsgame": "Yards/Game",
  "play_stuffed": "Stuffed %",
  "drives": "Total Drives",
  "drivesgame": "Drives/Game",
  "yardsdrive": "Yards/Drive",
  "playsdrive": "Plays/Drive",
  "success": "Success %",
  "red_zone_success": "Red Zone SR%",
  "third_down_success": "3rd Down SR%",
  "third_down_distance": "Avg Distance (3rd)",
  "late_down_success": "Late Down SR%",
  "early_down_EPA": "Early Down EPA/Play",
  "start_position": "Starting Field Position",
  "nonExplosiveEpaPerPlay": "Non-Expl EPA/Play",
  "line_yards": "Line Yards/Rush",
  "opportunity_rate": "Rush Opp %",
  "total_available_yards": "Total Available Yards",
  "total_gained_yards": "Total Gained Yards",
  "available_yards_pct": "Available Yards %",
  "adj_epa": "Adj EPA/Play",
  "strength_faced": "Strength Faced",
  "EPAdropback": "EPA/Dropback",
  "EPArush": "EPA/Rush"
}

export const SESSION_FAVORITES_DEFAULT = { teams: [], games: [] };
export const EVENT_KEY_TRENDS_METRIC_CHANGED = 'TrendsMetricChanged';