ServerName api.gameonpaper.com
<VirtualHost *:80>
    ServerName api.gameonpaper.com

    Redirect permanent / https://api.gameonpaper.com/
RewriteEngine on
RewriteCond %{SERVER_NAME} =api.gameonpaper.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
<VirtualHost *:443>
    ServerName api.gameonpaper.com
    Protocols h2 http/1.1
    DocumentRoot /frontend/public
    ErrorLog ${APACHE_LOG_DIR}/gameonpaper.com-error.log
    CustomLog ${APACHE_LOG_DIR}/gameonpaper.com-access.log combined
    SSLEngine On
    ProxyPass / http://0.0.0.0:5000/
    ProxyPassReverse / http://0.0.0.0:5000/
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /etc/letsencrypt/live/gameonpaper.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/gameonpaper.com/privkey.pem
</VirtualHost>