ServerName gameonpaper.com
<VirtualHost *:80>
    ServerName gameonpaper.com
    ServerAlias www.gameonpaper.com

    Redirect permanent / https://gameonpaper.com/
RewriteEngine on
RewriteCond %{SERVER_NAME} =gameonpaper.com [OR]
RewriteCond %{SERVER_NAME} =www.gameonpaper.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
<VirtualHost *:443>
    ServerName gameonpaper.com
    ServerAlias www.gameonpaper.com
   Protocols h2 http/1.1
  <If "%{HTTP_HOST} == 'www.gameonpaper.com'">
    Redirect permanent / https://gameonpaper.com/
  </If>
  DocumentRoot /frontend/public
  ErrorLog ${APACHE_LOG_DIR}/gameonpaper.com-error.log
  CustomLog ${APACHE_LOG_DIR}/gameonpaper.com-access.log combined
  SSLEngine On
  ProxyPass /api/v2 http://0.0.0.0:5000/
  ProxyPassReverse /api/v2 http://0.0.0.0:5000/
  ProxyPass / http://0.0.0.0:8000/
  ProxyPassReverse / http://0.0.0.0:8000/
  Include /etc/letsencrypt/options-ssl-apache.conf
  SSLCertificateFile /etc/letsencrypt/live/gameonpaper.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/gameonpaper.com/privkey.pem
</VirtualHost>