import scheduleMap from '../static/schedule.json' with { type: "json" };
import groupMap from '../static/groups.json' with { type: "json" };  
import seasonGroupMap from '../static/season_groups.json' with { type: "json" };
import type { ESPNScheduleEntry } from './espn';

export type ScheduleWeek = ESPNScheduleEntry & {
    year: string;
    type: string;
}
export type ScheduleMap = Record<string, ScheduleWeek[]>
export const GLOBAL_SCHEDULE_MAP: ScheduleMap = (scheduleMap as ScheduleMap);

export interface ScheduleGroup {
    id: number;
    name: string;
}
export const GLOBAL_GROUP_LIST: ScheduleGroup[] = (groupMap as ScheduleGroup[]);

// Each season's conference filter under that season's names, keyed by the fall
// year. Generated by scripts/update_groups.py from the cfb_groups release; never
// hand-edit it.
export const SEASON_GROUP_MAP: Record<string, ScheduleGroup[]> = seasonGroupMap;

/** The conference filter for a season; today's static list for a season the file lacks. */
export function groupsForSeason(season: number | string): ScheduleGroup[] {
    return SEASON_GROUP_MAP[String(season)] ?? GLOBAL_GROUP_LIST;
}
