server {
    listen 8080;
    listen [::]:8080;
    server_name gameonpaper.com  www.gameonpaper.com;
    resolver 1.1.1.1 [::1]:5353 valid=30s;
    include mime.types;

    if ($http_user_agent ~* "(AdsBot-Google|Amazonbot|anthropic-ai|Applebot|Applebot-Extended|AwarioRssBot|AwarioSmartBot|Bytespider|CCBot|ChatGPT-User|ClaudeBot|Claude-Web|cohere-ai|DataForSeoBot|Diffbot|FacebookBot|FriendlyCrawler|Google-Extended|GoogleOther|GPTBot|img2dataset|ImagesiftBot|magpie-crawler|Meltwater|omgili|omgilibot|peer39_crawler|peer39_crawler/1.0|PerplexityBot|PiplBot|scoop.it|Seekr|YouBot)"){
        return 403;
    }

    set $cdn_domain "gop.nyc3.cdn.digitaloceanspaces.com";

    # svg, fonts
    location ~* ^/assets/(.*)\.(svgz?|ttf|ttc|otf|eot|woff2?)$ {
        proxy_pass https://$cdn_domain/assets/$1.$2;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $cdn_domain;
        proxy_set_header Origin $cdn_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;

		add_header Access-Control-Allow-Origin "*";
		expires 7d;
		access_log off;
	}

    location ~* ^/assets/(.*)$ {
        proxy_pass https://$cdn_domain/assets/$1;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $cdn_domain;
        proxy_set_header Origin $cdn_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;

		expires 7d;
		access_log off;
	}
    
    location ~ {
        proxy_pass http://node:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
	}

    # # All other HTML pages
    # location ~ ^/cfb/game/([0-9]+)$ {
    #     default_type text/html;

    #     proxy_pass https://$cdn_domain/games/$1.html;
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    #     proxy_set_header Host $cdn_domain;
    #     proxy_set_header Origin $cdn_domain;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_ssl_server_name on;
    #     proxy_set_header Content-Type text/html;
    #     proxy_set_header Content-Encoding utf8;
    # }
}