name = "gameonpaper-dev"
main = "handlers/server.js"
compatibility_date = "2026-05-24"
compatibility_flags = [
    "nodejs_compat",
    "enable_nodejs_http_modules",
    "enable_nodejs_http_server_modules",
]
base_dir = "."

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]
fallthrough = true

[dev]
port = 8080

[assets]
directory = "./public"

[observability]
enabled = true

[vars]
PORT = 8080