[project]
name = "gameonpaper-python"
version = "0.1.1"
requires-python = ">=3.14"
dependencies = [
    "Flask",
    "sportsdataverse>=0.1.4",
    "gunicorn",
    "flask-compress>=1.25",
    "orjson>=3.13",
    "psycopg[binary]>=3.3",
]
[tool.uv.sources]
sportsdataverse = { git = "https://github.com/sportsdataverse/sportsdataverse-py", branch = "main" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
