name: deploy

on:
  push:
    branches:
      - AE/cloudflare
  # repository_dispatch:
  #   types: [ deploy ]
  workflow_dispatch:
  # workflow_call:

jobs:
  # deploy-web:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v7
  #       with:
  #         repository: saiemgilani/game-on-paper-app
  #     - uses: cloudflare/wrangler-action@v4
  #       env: 
  #         PYTHON_HTTP_TOKEN: ${{ secrets.PYTHON_HTTP_TOKEN }}
  #         SDV_AUTH_TOKEN: ${{ secrets.SDV_AUTH_TOKEN }}
  #         APP_VERSION: ${{ github.sha }}
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         workingDirectory: "./astro"
  #         secrets: |
  #           PYTHON_HTTP_TOKEN
  #           SDV_AUTH_TOKEN
  #         vars: |
  #           APP_VERSION
  #         preCommands: |
  #           npm install --save
  #           npm run build
  #     - name: Check that web is live
  #       uses: jtalk/url-health-check-action@v5
  #       with:
  #         url: https://game-on-paper-astro.akeaswaran.workers.dev/ #https://gameonpaper.com|http://gameonpaper.com|https://www.gameonpaper.com|http://www.gameonpaper.com
  #         follow-redirect: false
  #         max-attempts: 10
  #         retry-delay: 5s

  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: saiemgilani/game-on-paper-app
      # - name: Publish Python container to GitHub
      #   uses: mr-smithers-excellent/docker-build-push@b6e94a8afeb0887d5cddb51a1db7dcc6bb6864ba
      #   with:
      #     image: saiemgilani/game-on-paper-python-api
      #     registry: ghcr.io
      #     username: ${{ secrets.GH_USERNAME }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     directory: ./python
      #     dockerfile: ./python/Dockerfile
      #     tags: latest
      # - name: Update SHA for docker compose
      #   run: |
      #     DOCKER_COMPOSE_CONTENT="$(cat ./docker-compose.do.yml)"
      #     SHA="${{ github.sha }}"
      #     DOCKER_COMPOSE_CONTENT="${DOCKER_COMPOSE_CONTENT//REPLACE_ME/$SHA}"
      #     echo $DOCKER_COMPOSE_CONTENT > ./docker-compose.do.yml
      #     cat ./docker-compose.do.yml
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.API_HOST }} >> ~/.ssh/known_hosts
      - name: Restart Docker Compose
        env:
          SSH_HOST: ${{ secrets.API_HOST }}
          SSH_USER: ${{ secrets.API_USERNAME }}
          SSH_PORT: ${{ secrets.PORT }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          sftp -i ~/.ssh/deploy_key -P $SSH_PORT $SSH_USER@$SSH_HOST bash << 'ENDSSH'
            put docker-compose.do.yml docker-compose.yml
          ENDSSH

          ssh -i ~/.ssh/deploy_key -p $SSH_PORT $SSH_USER@$SSH_HOST bash << 'ENDSSH'
            set -e
            docker stop $(docker ps -a -q) || true
            docker system prune --force
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker-compose pull
            docker-compose -f docker-compose.yml up -d
          ENDSSH

      - name: Check that API is live
        uses: jtalk/url-health-check-action@v5
        with:
          url: https://api.gameonpaper.com/healthcheck|http://api.gameonpaper.com/healthcheck
          follow-redirect: false
          max-attempts: 10
          retry-delay: 5s